rename from zbrew to zospm

diff --git a/bin/zospmrestore b/bin/zospmrestore
--- a/bin/zospmrestore
+++ b/bin/zospmrestore
@@ -6,19 +6,19 @@
 syntax() {
 	echo "\
 Syntax:
-	zbrewrestore <sw> 
+	zospmrestore <sw> 
 Notes:
-	\$ZBREW_TMP/<sw>.dzp is where the archive will be written to
+	\$ZOSPM_TMP/<sw>.dzp is where the archive will be written to
 
 " >&2
      	exit 8
 }
 
-. zbrewsetenv
+. zospmsetenv
 
 if ! [ $# -eq 1 ]; then
 	echo "Expected 1 parameter but $# parameters specified ($*)" >&2
-        echo "zbrewrestore <sw>" >&2
+        echo "zospmrestore <sw>" >&2
  	syntax
         exit 8
 fi  
@@ -26,9 +26,9 @@ sw=$1
 ussname=$(echo $sw | tr '[:upper:]' '[:lower:]');
 zosname=$(echo $sw | tr '[:lower:]' '[:upper:]');
 prefix=`echo "${ussname}" | awk '{ print substr($sw, 0, 3) }'`
-dunzipout="${ZBREW_TMP}/$$dzip.out"
+dunzipout="${ZOSPM_TMP}/$$dzip.out"
 
-dunzip -s1G "${ZBREW_TMP}/${ussname}.dzp" "${ZBREW_TGT_HLQ%.*}" >${dunzipout} 2>&1
+dunzip -s1G "${ZOSPM_TMP}/${ussname}.dzp" "${ZOSPM_TGT_HLQ%.*}" >${dunzipout} 2>&1
 rc=$?
 if [ $rc -gt 4 ]; then
 	# Filter on 'empty dataset' (0ADR744W) message and if that is the only non-informational, treat the unzip as a pass
@@ -37,13 +37,13 @@ if [ $rc -gt 4 ]; then
 		rc=0
 		rm -f "${dunzipout}"
 	else
-		echo "zbrewrestore: Restore of archive ${archive} failed." >&2
+		echo "zospmrestore: Restore of archive ${archive} failed." >&2
 		cat "${dunzipout}" >&2
 		rm -f "${dunzipout}"
 		exit $rc
 	fi
 fi
 
-zbrewmount -m -t $sw
+zospmmount -m -t $sw
 
 exit $rc
